In [1]:
%pylab inline

Populating the interactive namespace from numpy and matplotlib


In [2]:
import pandas as pd

In [6]:
from sklearn.cluster import KMeans

In [12]:
data = pd.read_csv('/Users/alehmann/Documents/Documents/HIH/BDA/BDA2017/data/kmeans/2015-05-26_17-11-46.csv')
data.index = data['loggingTime']
data

loggingTime  loggingSample  \
loggingTime                                                       
2015-05-26 17:11:47.040  2015-05-26 17:11:47.040              1   
2015-05-26 17:11:47.121  2015-05-26 17:11:47.121              2   
2015-05-26 17:11:47.126  2015-05-26 17:11:47.126              3   
2015-05-26 17:11:47.131  2015-05-26 17:11:47.131              4   
2015-05-26 17:11:47.134  2015-05-26 17:11:47.134              5   
2015-05-26 17:11:47.137  2015-05-26 17:11:47.137              6   
2015-05-26 17:11:47.140  2015-05-26 17:11:47.140              7   
2015-05-26 17:11:47.209  2015-05-26 17:11:47.209              8   
2015-05-26 17:11:47.213  2015-05-26 17:11:47.213              9   
2015-05-26 17:11:47.216  2015-05-26 17:11:47.216             10   
2015-05-26 17:11:47.221  2015-05-26 17:11:47.221             11   
2015-05-26 17:11:47.225  2015-05-26 17:11:47.225             12   
2015-05-26 17:11:47.249  2015-05-26 17:11:47.249             13   
2015-05-26 17:11:47.253  2015-05-26 17:11:47.253             14   
2015-05-26 17:11:47.260  2015-05-26 17:11:47.260             15   
2015-05-26 17:11:47.265  2015-05-26 17:11:47.265             16   
2015-05-26 17:11:47.268  2015-05-26 17:11:47.268             17   
2015-05-26 17:11:47.273  2015-05-26 17:11:47.273             18   
2015-05-26 17:11:47.276  2015-05-26 17:11:47.276             19   
2015-05-26 17:11:47.280  2015-05-26 17:11:47.280             20   
2015-05-26 17:11:47.283  2015-05-26 17:11:47.283             21   
2015-05-26 17:11:47.345  2015-05-26 17:11:47.345             22   
2015-05-26 17:11:47.422  2015-05-26 17:11:47.422             23   
2015-05-26 17:11:47.438  2015-05-26 17:11:47.438             24   
2015-05-26 17:11:47.737  2015-05-26 17:11:47.737             25   
2015-05-26 17:11:47.827  2015-05-26 17:11:47.827             26   
2015-05-26 17:11:47.915  2015-05-26 17:11:47.915             27   
2015-05-26 17:11:47.919  2015-05-26 17:11:47.919             28   
2015-05-26 17:11:48.161  2015-05-26 17:11:48.161             29   
2015-05-26 17:11:48.348  2015-05-26 17:11:48.348             30   
...                                          ...            ...   
2015-05-26 17:35:33.441  2015-05-26 17:35:33.441         129652   
2015-05-26 17:35:33.447  2015-05-26 17:35:33.447         129653   
2015-05-26 17:35:33.451  2015-05-26 17:35:33.451         129654   
2015-05-26 17:35:33.455  2015-05-26 17:35:33.455         129655   
2015-05-26 17:35:33.461  2015-05-26 17:35:33.461         129656   
2015-05-26 17:35:33.464  2015-05-26 17:35:33.464         129657   
2015-05-26 17:35:33.467  2015-05-26 17:35:33.467         129658   
2015-05-26 17:35:33.473  2015-05-26 17:35:33.473         129659   
2015-05-26 17:35:33.476  2015-05-26 17:35:33.476         129660   
2015-05-26 17:35:33.479  2015-05-26 17:35:33.479         129661   
2015-05-26 17:35:33.483  2015-05-26 17:35:33.483         129662   
2015-05-26 17:35:33.511  2015-05-26 17:35:33.511         129663   
2015-05-26 17:35:33.571  2015-05-26 17:35:33.571         129664   
2015-05-26 17:35:33.576  2015-05-26 17:35:33.576         129665   
2015-05-26 17:35:33.581  2015-05-26 17:35:33.581         129666   
2015-05-26 17:35:33.585  2015-05-26 17:35:33.585         129667   
2015-05-26 17:35:33.590  2015-05-26 17:35:33.590         129668   
2015-05-26 17:35:33.593  2015-05-26 17:35:33.593         129669   
2015-05-26 17:35:33.596  2015-05-26 17:35:33.596         129670   
2015-05-26 17:35:33.600  2015-05-26 17:35:33.600         129671   
2015-05-26 17:35:33.606  2015-05-26 17:35:33.606         129672   
2015-05-26 17:35:33.611  2015-05-26 17:35:33.611         129673   
2015-05-26 17:35:33.615  2015-05-26 17:35:33.615         129674   
2015-05-26 17:35:33.624  2015-05-26 17:35:33.624         129675   
2015-05-26 17:35:33.635  2015-05-26 17:35:33.635         129676   
2015-05-26 17:35:33.727  2015-05-26 17:35:33.727         129677   
2015-05-26 17:35:33.734  2015-05-26 17:35:33.734         129678   
2015-05-26 17:35:

In [26]:
type(data)

pandas.core.frame.DataFrame

In [28]:
acc = data[['accelerometerAccelerationX','accelerometerAccelerationY','accelerometerAccelerationZ']]


In [18]:
model = KMeans(n_clusters=6)

In [24]:
model.fit(acc)

KMeans(algorithm='auto', copy_x=True, init='k-means++', max_iter=300,
    n_clusters=6, n_init=10, n_jobs=1, precompute_distances='auto',
    random_state=None, tol=0.0001, verbose=0)

In [25]:
model.cluster_centers_

array([[ 0.4718568 ,  0.02426922, -0.96084923],
       [ 0.2446789 , -0.03541355, -1.0214022 ],
       [ 0.13161593,  0.11739872, -1.05370625],
       [-0.00434868, -0.19327368, -1.02134953],
       [ 0.00330167, -0.06526849, -1.04685   ],
       [ 0.26427938, -0.14144462, -0.99495916]])

In [20]:
model.cluster_centers_

array([[ 0.47198024,  0.02441407, -0.96085007],
       [ 0.00337511, -0.0652809 , -1.04684414],
       [ 0.13138075,  0.11751682, -1.05376336],
       [-0.00453   , -0.19326816, -1.02135903],
       [ 0.26417088, -0.14123191, -0.99500562],
       [ 0.24468234, -0.03531259, -1.02142314]])

In [22]:
res = model.predict(acc)

In [23]:
res

array([3, 3, 3, ..., 5, 5, 5], dtype=int32)

In [29]:
len(res)

129681